### ISSUE TITLE
[Feature] Add changelog

### ISSUE THREAD

**Issue by rwaight** [rwaight/actions#113]
### Other request synopsis

Create or update a changelog

### Other request requirements

Update (or create) a changelog.

Can start with this [update changelog note](https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#update-changelog) that uses [git-chglog](https://github.com/git-chglog/git-chglog/)
> Raises a pull request to update the CHANGELOG.md file based on the tagged commit of the release. Note that [git-chglog](https://github.com/git-chglog/git-chglog/) requires some configuration files to exist in the repository before this workflow will work.

```yml
name: Update Changelog
on:
  release:
    types: [published]
jobs:
  updateChangelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update Changelog
        run: |
          curl -o git-chglog -L https://github.com/git-chglog/git-chglog/releases/download/0.9.1/git-chglog_linux_amd64
          chmod u+x git-chglog
          ./git-chglog -o CHANGELOG.md
          rm git-chglog

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: update changelog
          title: Update Changelog
          body: Update changelog to reflect release changes
          branch: update-changelog
          base: main
```

It looks like there are a few actions that use `git-chglog` already:
- https://github.com/nuuday/github-changelog-action
- https://github.com/pfandie/generate-changelog-action
