### ISSUE TITLE
[Security] Respond to tj-actions/changed-files compromise

### ISSUE THREAD

**Issue by rwaight** [rwaight/actions#315]
## Issue overview

Track and respond to the tj-actions/changed-files compromise:
- [GitHub Advisory `CVE-2025-30066`](https://github.com/advisories/GHSA-mrrh-fwg8-r2c3)

### Issue synopsis

Via:
- [semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised](https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/)
- [stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised](https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised)

This repo has a local copy of the `tj-actions/changed-files` action.  The **test-actions** workflow is set to run with the following options:
```yml
on:
  pull_request:
    branches:
      - main
    types: [review_requested]
```

It _does not appear_ this repo is impacted; however, this issue is opened to track changes and updates.

## Compromise details reported in the repo

Compromise details reported in the repo at:
- [tj-actions/changed-files#2463](https://github.com/tj-actions/changed-files/issues/2463)
- [tj-actions/changed-files#2464](https://github.com/tj-actions/changed-files/issues/2464)

_It appears that_ a malicious commit made on 2025-03-14 attempts to dump the repo's secrets to the workflow log.

The maintainer has already addressed the issue and reversed the malicious changes.

This repo has a local copy of the `tj-actions/changed-files` action.  The **test-actions** workflow is set to run with the following options:
```yml
on:
  pull_request:
    branches:
      - main
    types: [review_requested]
```
