### ISSUE TITLE
Release drafter v6.1.0 does not find existing draft releases and thus creates multiple draft releases

### ISSUE THREAD

**Issue by rwaight** [rwaight/actions#347]
### What compontent is impacted by this problem?

actions

### What action category (group) is impacted by this problem?

releases

### What happened?

[Release Drafter v6.1.0](https://github.com/release-drafter/release-drafter/releases/tag/v6.1.0) introduced a regression that causes it to create multiple duplicate draft releases instead of updating existing ones.
- [Release Drafter `v6.1.0` release notes](https://github.com/release-drafter/release-drafter/releases/tag/v6.1.0)
- [Release Drafter commit `b1476f6`](https://github.com/release-drafter/release-drafter/commit/b1476f6e6eb133afa41ed8589daba6dc69b4d3f5)

### Steps to reproduce

See [`release-drafter#1425`](https://github.com/release-drafter/release-drafter/issues/1425), this is a known issue that has more information on the nature of the problem.

Some workarounds are to either:
- Pin release-drafter to `v6.0.0` which correctly finds and updates existing draft releases; or
- Set `prerelease` and `include-pre-releases` to the same value within the release drafter config

```yml
# Known Release Drafter bug, see: 
#       https://github.com/release-drafter/release-drafter/issues/1425
# 
# Do not mark the draft release as a pre-release
prerelease: false
# Do not include pre-releases in the draft release
include-pre-releases: false
```

#### Other references

- https://github.com/release-drafter/release-drafter/pull/1385#discussion_r1923883076

### Expected behavior

Release drafter should find and update an existing draft release, not create a new draft release.
